# General
url: https://vikpe.org/github-pages-starter
encoding: utf-8

# Github
repository: vikpe/github-pages-starter

# Handling Reading
safe: true
include:
  - _pages

exclude:
  - node_modules/
  - project/
  - src/
  - .gitignore
  - bs-config.js
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - gulpfile.paths.js
  - readme.md
  - yarn.lock
  - yarn-error.log

# Conversion
markdown: kramdown
incremental: false
highlighter: rouge

# Outputting
permalink: pretty
timezone: Europe/Stockholm

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false

# Custom settings
custom_settings:
  is_published: false
  name: GitHub Pages starter
  description: Bare minimum GitHub Pages starter for rapid development.
  google_analytics_tracking_code: false
