# Site Variables
url: https://vikpe.org/github-pages-starter

# Custom settings (GitHub Pages starter)
custom_settings:
  # required
  is_development: false
  is_published: false

  # optional/convenience
  name: GitHub Pages starter
  description: Fast rendering, live reload, GitHub Pages ready.
  google_analytics_tracking_code: false

# Handling Reading
safe: true
include:
  - _pages

keep_files:
  - assets/css/styles.min.css

exclude:
  - assets/css/styles.min.css
  - .idea/
  - node_modules/
  - project/
  - src/
  - .gitignore
  - bs-config.js
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - gulpfile.paths.js
  - readme.md
  - yarn.lock
  - yarn-error.log

# Conversion
markdown: kramdown

# Output
permalink: pretty
timezone: Europe/Stockholm

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false
