# Site Variables
url: https://vikpe.org/github-pages-starter

# Custom settings (GitHub Pages starter)
custom_settings:
  # required
  is_development: false

  # optional/convenience
  name: GitHub Pages starter
  description: Fast builds, live reload, GitHub Pages ready.

# Handling / Reading
source: .
safe: true
include:
  - _pages

keep_files:
  - assets # generate by gulp

exclude:
  - _data/rev-manifest.json
  - .idea/
  - node_modules/
  - project/
  - src/
  - .gitignore
  - bs-config.js
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - gulpfile.paths.js
  - LICENSE
  - package.json
  - readme.md
  - yarn.lock
  - yarn-error.log

# Conversion
markdown: kramdown

# Output
permalink: pretty
timezone: Europe/Stockholm
destination: ../public

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false
